/**
 * Teardown annotation content.
 *
 * Single source of truth for all engineering annotations shown when
 * teardown mode is active. Each section's entries are generated by a
 * factory function that accepts computed values from the component,
 * so the content stays centralized while dynamic data is injected
 * type-safely.
 *
 * To add or edit teardown text for any visualization, change it here.
 * Components import these factories and pass the result to TeardownPanel.
 */

export type TeardownEntry = {
  label: string;
  value: string;
};

// ---------------------------------------------------------------------------
// Sensemaking Annotations
// ---------------------------------------------------------------------------

export const sensemakingTeardownEntries: TeardownEntry[] = [
  {
    label: "Theoretical grounding",
    value:
      'Klein, G. et al. (2007). A Data-Frame Theory of Sensemaking. Expertise Out of Context. Six activities: elaborating, questioning, connecting, comparing, framing, re-framing. Each maps to a computational design requirement.',
  },
  {
    label: "Systems-theoretic mapping",
    value:
      "Leveson, N. (2012). Engineering a Safer World. STAMP control structure concepts (process models, sensor independence, feedback loops) provide the safety engineering constraints on each sensemaking activity.",
  },
  {
    label: "Design claim",
    value:
      'Abstract Claim 5: "The architecture embeds sensemaking theory and systems-theoretic accident modeling as design requirements." This grid is the evidence. Each chart below is a working instantiation of both frameworks operating simultaneously.',
  },
];

// ---------------------------------------------------------------------------
// Corpus Summary
// ---------------------------------------------------------------------------

export function corpusTeardownEntries(opts: {
  corpusVersion: string;
}): TeardownEntry[] {
  return [
    {
      label: "Corpus version",
      value: `"${opts.corpusVersion}". Frozen label in the documents table. All queries filter on this value so the dashboard shows a reproducible snapshot, not live-ingested data.`,
    },
    {
      label: "Document count",
      value:
        "SELECT count(*) FROM documents WHERE corpus_version = ?. Each row is one fetched URL. Duplicate URLs with different corpus versions are separate rows.",
    },
    {
      label: "Source count",
      value:
        "SELECT count(DISTINCT source_id) FROM documents WHERE corpus_version = ?. Sources are domains, not individual journalists or bylines.",
    },
    {
      label: "Ingestion pipeline",
      value:
        "Wayback Machine CDX API → HTML fetch with id_ modifier → trafilatura text extraction → Vercel Blob (raw HTML) + Neon Postgres (metadata). Idempotent on content_hash.",
    },
  ];
}

// ---------------------------------------------------------------------------
// IVI Chart
// ---------------------------------------------------------------------------

export function iviTeardownEntries(opts: {
  windowDays: number;
  peakValue: number;
  peakDate: string;
  peakDiscourse: number;
  peakAuthoritative: number;
}): TeardownEntry[] {
  return [
    {
      label: "Formula",
      value:
        "IVI = discourse_count / authoritative_count. Values > 1.0 indicate public discourse outpacing authoritative response.",
    },
    {
      label: "Discourse sources",
      value:
        "Documents from source kinds: news, social, forum, podcast. Counted per rolling window.",
    },
    {
      label: "Authoritative sources",
      value:
        "Documents from source kinds: gov, aviation. FAA NOTAMs, DoD press releases, congressional statements.",
    },
    {
      label: "Rolling window",
      value: `${opts.windowDays}-day sliding window. Each bar represents the IVI value at that window's end date. Window choice balances temporal resolution against noise.`,
    },
    {
      label: "Data lineage",
      value:
        "Wayback Machine CDX API snapshots → trafilatura extraction → source kind classification (hand-labeled per domain) → windowed count ratio.",
    },
    {
      label: "Peak interpretation",
      value: `Peak value ${opts.peakValue.toFixed(2)} on ${opts.peakDate}. Discourse count: ${opts.peakDiscourse}. Authoritative count: ${opts.peakAuthoritative}.`,
    },
    {
      label: "Assumption",
      value:
        "Source kind labels are assigned per domain, not per document. A news domain is always 'discourse' even if a specific article quotes official sources directly.",
    },
  ];
}

// ---------------------------------------------------------------------------
// Hypothesis Chart
// ---------------------------------------------------------------------------

export function hypothesisTeardownEntries(opts: {
  maxEntropyBits: number;
  minEntropy: number;
  minEntropyPct: number;
}): TeardownEntry[] {
  return [
    {
      label: "Scoring model",
      value:
        "Claude Haiku 4.5 (claude-haiku-4-5-20251001). Prompt version h15-v1. Each document scored independently against all five hypotheses.",
    },
    {
      label: "Per-document scoring",
      value:
        "LLM assigns P(H1)..P(H5) per document, constrained to sum to 1.0. Stored in document_hypothesis_scores table with rationale text.",
    },
    {
      label: "Daily aggregation",
      value:
        "Daily distribution = mean of per-document probability vectors for documents published that day. Stored in hypothesis_distributions table.",
    },
    {
      label: "Entropy formula",
      value: `H = -Σ p_i × log2(p_i) over i = H1..H5. Maximum entropy for 5 hypotheses = log2(5) = ${opts.maxEntropyBits.toFixed(4)} bits (uniform distribution).`,
    },
    {
      label: "Bar height = entropy",
      value:
        "Each bar's total height is the Shannon entropy of that day's distribution. Higher bars = more uncertainty preserved. Color segments show each hypothesis's probability share.",
    },
    {
      label: "Structured uncertainty claim",
      value: `Floor entropy ${opts.minEntropy.toFixed(2)} bits (${opts.minEntropyPct.toFixed(0)}% of max). The system never collapses to a single hypothesis. This is the central empirical claim of the SQM method.`,
    },
    {
      label: "Assumption",
      value:
        "LLM probability assignments are treated as calibrated. No ground-truth validation of individual scores exists yet. The claim is structural (entropy preservation), not calibration accuracy.",
    },
  ];
}

// ---------------------------------------------------------------------------
// NVD Chart
// ---------------------------------------------------------------------------

export function nvdTeardownEntries(opts: {
  peakNarrative: string;
  peakValue: number;
  peakDate: string;
  peakNarrativeVelocity: number;
  peakEvidenceVelocity: number;
}): TeardownEntry[] {
  return [
    {
      label: "Formula",
      value:
        "NVD = narrative_velocity / (evidence_velocity + 1). The +1 prevents division by zero when no corroborating evidence exists.",
    },
    {
      label: "Narrative velocity",
      value:
        "Count of documents matching this narrative's keyword classifier within the rolling window. Not weighted by source authority.",
    },
    {
      label: "Evidence velocity",
      value:
        "Count of documents providing independent evidence supporting the narrative's core claim. Determined by LLM classification, not keyword match.",
    },
    {
      label: "Threshold",
      value:
        "NVD = 1.0 (solid gridline) means narrative and evidence are spreading at equal rates. Above 1.0: narrative outpacing evidence. Below 1.0: evidence accumulating faster than narrative spread.",
    },
    {
      label: "Rolling window",
      value:
        "3-day window. Shorter than the IVI 7-day window because narrative velocity spikes are sharper and more transient than institutional response gaps.",
    },
    {
      label: "Narrative definitions",
      value:
        "Eight narratives defined in data/nj-drones/narratives.yaml. Five shown here (non-zero NVD). Narrative keyword matchers and evidence classifiers are separate systems.",
    },
    {
      label: "Peak detail",
      value: `${opts.peakNarrative}: NVD ${opts.peakValue.toFixed(2)} on ${opts.peakDate}. Narrative velocity: ${opts.peakNarrativeVelocity} docs. Evidence velocity: ${opts.peakEvidenceVelocity} docs.`,
    },
    {
      label: "Assumption",
      value:
        "Narrative-to-document assignment is single-label (each document matches at most one narrative per window). Multi-narrative documents are assigned to the strongest match.",
    },
  ];
}

// ---------------------------------------------------------------------------
// Independence Table
// ---------------------------------------------------------------------------

export const independenceTeardownEntries: TeardownEntry[] = [
  {
    label: "Independence score",
    value:
      "independent_sources + 1. The +1 counts the originating source. Score of 1 = zero independent corroboration.",
  },
  {
    label: "Amplification ratio",
    value:
      "total_documents / independence_score. Measures how many outlets repeated the claim per independent source. High ratio + low score = echo chamber.",
  },
  {
    label: "Echo chamber threshold",
    value:
      "independence_score ≤ 2 AND amplification_ratio ≥ 3. These thresholds are hand-tuned for the NJ drones corpus. A more rigorous threshold derivation is deferred.",
  },
  {
    label: "Source role assignment",
    value:
      "Each domain is classified as 'origin' or 'amplifier' by tracing citation chains. Origin = first to publish the claim. Amplifier = republished or referenced the origin without adding independent evidence.",
  },
  {
    label: "Graph data",
    value:
      "Per-narrative source graph stored in signal_independence.graphData (JSONB). Contains domain, role, and document_count per source. Powers the React Flow visualization.",
  },
  {
    label: "Assumption",
    value:
      "Independence is assessed at the domain level, not the journalist level. Two articles from the same domain with different bylines count as one source. This is conservative: it may undercount independence in large newsrooms with genuinely independent desks.",
  },
];
